server:
  port: 8082
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
feign:
  client:
    config:
      default: #全局配置文件 更改此处可以指定服务设置参数
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    com.chen.user.feign.UserOrderFeign: debug